services:
  api:
    build: .
    container_name: mi-api
    environment:
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma migrate deploy && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mi-db
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: midb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
